#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# RECONFIGURE THE APP (UPDATE CONF, APPLY MIGRATIONS...)
#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template=".env.local" --destination="$install_dir/.env.local"

#=================================================
# CONFIGURATION FOR SUBPATH
#=================================================

ynh_safe_rm "$install_dir/public/manifest.json"
ynh_safe_rm "$install_dir/next.config.js"

if [ "$path" = "/" ]; then
	next_path=""
else
	next_path=$path
fi

ynh_config_add --template="manifest.json" --destination="$install_dir/public/manifest.json"

ynh_config_add --template="next.config.js" --destination="$install_dir/next.config.js"

ynh_replace --match="src={useColorModeValue(\"/banner_light.svg\", \"/banner_dark.svg\")}" --replace="src={useColorModeValue(\"$next_path/banner_light.svg\", \"$next_path/banner_dark.svg\")}" --file="$install_dir/components/Header.tsx"

ynh_replace --match="href=\"/favicon" --replace="href=\"$next_path/favicon" --file="$install_dir/components/CustomHead.tsx"

ynh_replace --match="href=\"/apple" --replace="href=\"$next_path/apple" --file="$install_dir/components/CustomHead.tsx"

ynh_replace --match="href=\"/manifest" --replace="href=\"$next_path/manifest" --file="$install_dir/components/CustomHead.tsx"

chown $app:www-data "$install_dir/public/manifest.json"
chown $app:www-data "$install_dir/next.config.js"
chmod 664 "$install_dir/public/manifest.json"
chmod 664 "$install_dir/next.config.js"

#=================================================
# REBUILD AND INSTALL THE APP
#=================================================
ynh_script_progression "Rebuilding the app..."

pushd "$install_dir"
	ynh_hide_warnings corepack enable && corepack prepare yarn@4.13.0 --activate
	ynh_hide_warnings ynh_exec_as_app yarn config set enableTelemetry 0
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app yarn run next telemetry disable
	ynh_hide_warnings ynh_exec_as_app yarn build
popd

chown -R $app:$app "$install_dir/node_modules"
chown -R $app:$app "$install_dir/.next"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="alternative to google translate" --log="/var/log/$app/$app.log"

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
